# Generated by Django 2.1.4 on 2018-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='Authors',
            field=models.ManyToManyField(related_name='Authors', to='Publications.Author'),
        ),
    ]
