# Generated by Django 2.1.4 on 2018-12-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0002_auto_20181229_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Institute',
        ),
    ]
