# Generated by Django 2.0 on 2018-12-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveProjects',
            new_name='ActiveProject',
        ),
        migrations.RenameModel(
            old_name='PastProjects',
            new_name='PastProject',
        ),
    ]
