# Generated by Django 2.0 on 2018-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181218_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=200)),
                ('paper_abstract', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='pastproject',
            name='past_project_abstract',
            field=models.CharField(default='Does not Exit', max_length=1000),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='past_project_context',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='past_project_join_us',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='past_project_name',
            field=models.CharField(default='Unnamed Project', max_length=30),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='past_project_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='past_project_team',
            field=models.ManyToManyField(related_name='past_project_team', to='projects.DummyPeopleModel'),
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='project_paper',
        ),
        migrations.AddField(
            model_name='pastproject',
            name='past_project_paper',
            field=models.ManyToManyField(blank=True, related_name='past_project_paper', to='projects.Papers'),
        ),
        migrations.AddField(
            model_name='activeproject',
            name='project_paper',
            field=models.ManyToManyField(blank=True, related_name='project_paper', to='projects.Papers'),
        ),
    ]
