# Generated by Django 2.0 on 2018-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Picture', models.ImageField(upload_to='')),
                ('Bio', models.TextField()),
                ('Resume', models.TextField()),
                ('Github', models.TextField()),
                ('Gmail', models.TextField()),
                ('LinkedIn', models.TextField()),
                ('Website', models.TextField()),
                ('Category', models.TextField()),
            ],
        ),
    ]
