# Generated by Django 2.0 on 2018-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='Github',
            field=models.CharField(blank='true', max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='Gmail',
            field=models.CharField(blank='true', max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='LinkedIn',
            field=models.CharField(blank='true', max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='Resume',
            field=models.CharField(blank='true', max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='Website',
            field=models.CharField(blank='true', max_length=50),
        ),
    ]
