# Generated by Django 2.1.4 on 2018-12-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_auto_20181217_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Github',
            field=models.CharField(max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Gmail',
            field=models.CharField(max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='people',
            name='LinkedIn',
            field=models.CharField(max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Picture',
            field=models.CharField(max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Resume',
            field=models.CharField(max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Website',
            field=models.CharField(max_length=100, null='true'),
        ),
    ]
