# Generated by Django 2.0 on 2018-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_abstract', models.CharField(max_length=1000)),
                ('project_paper', models.CharField(max_length=1000)),
                ('project_join_us', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DummyPeopleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PastProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='activeprojects',
            name='project_team',
            field=models.ManyToManyField(help_text='Team that works on this Project', to='projects.DummyPeopleModel'),
        ),
    ]
