# Generated by Django 2.1.4 on 2019-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190119_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_abstract', models.CharField(max_length=1000)),
                ('project_team', models.CharField(blank=True, max_length=1000)),
                ('project_join_us', models.CharField(blank=True, max_length=1000)),
                ('project_photo', models.ImageField(blank=True, upload_to='')),
                ('project_context', models.CharField(blank=True, max_length=1000)),
                ('is_past', models.BooleanField()),
                ('project_paper', models.ManyToManyField(blank=True, related_name='project_paper', to='projects.Papers')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_paper',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_team',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
